### ISSUE TITLE
【chef】/var/www/htmlフォルダに権限を与える

### ISSUE THREAD

**Issue by naoki0531** [yamaguchi05/CTFW#3]
表題の箇所がSambaのネットワークフォルダになっているが、
権限が付与されていないためファイルが配置できない。
レシピで777を付与するように変更する

**Comment by yamaguchi05** [comment]
0644を0777に変更
https://github.com/yamaguchi05/CTFW/pull/8

**Comment by naoki0531** [comment]
これはsambaの設定ファイルの権限であり、
/var/www/htmlの権限ではありません！

chefのdirectoryという書き方で変更できます。
調べてみてください

**Comment by yamaguchi05** [comment]
承知致しました。↑は閉じます！

**Comment by yamaguchi05** [comment]
再度修正してみました
https://github.com/yamaguchi05/CTFW/pull/10

**Comment by naoki0531** [comment]
取り入れたので動作確認待ちです！

**Comment by naoki0531** [comment]
動作確認できました！
