### ISSUE TITLE
【その他】環境構築説明スライドに概要を追加する

### ISSUE THREAD

**Issue by naoki0531** [yamaguchi05/CTFW#4]
・この構成でどんなことができるのか？
・スライドで何を伝えたいのか？
（内部まで詳しく知らなくても、大まかに何が起きているのかとコマンドさえ覚えてくれれば問題ないという事
をそれぞれスライドの前半に追記する。

**Comment by yamaguchi05** [comment]
■今日のゴール
・環境構築の流れをおおまかにつかむ
・紹介するコマンドを覚えていただければ、
　不自由なく環境構築できるということを知る

■インフラ自動化ツール chef を用います！
・chefとは？（丸山さんの勉強会資料を引っ張る
・case1 case2 chefの利点（丸山さんの勉強会資料を引っ張る
・Chefでできる事　（最後の方にあるスライドを前に持ってくる）

※上記を加えるにあたって以下ページを削除
・git cloneのあとの1ページ
　「これらの環境構築を記述するファイルをバージョン管理する事で、
　環境を自分で管理する必要がなくなる。」

**Comment by naoki0531** [comment]
ちょっとやってみたら、chefのコマンドをvagrantfileに記述したら

vagrant up --provision　って入力するだけで中でchefが自動実行されました。
これも発表に入れますか

**Comment by yamaguchi05** [comment]
発表完了

**Comment by yamaguchi05** [comment]
発表完了
